theme: jekyll-theme-minimal
title: Econometría Avanzada II
description: En este repositorio se encuentra el material del curso de Econometría Avanzada II del PhD/Maestría en Economía de la Universidad EAFIT (Medellín-Colombia)